### ISSUE TITLE
MP2 energy calculation reports DF-SCS-MP2 energy

### ISSUE THREAD

**Issue by dbmagers** [psi4/psi4webmo#6]
Currently if you select MP2 as the Method in WebMO the DF-SCS-MP2 energy is parsed.

So I have two questions:
1)  Should we parse the DF-MP2 energy instead?  I'm not very familiar with spin-component scaling personally.  This could just be an accident and a quick fix since the parser looks for "MP2 TOTAL ENERGY" and finds it first from the bottom of the output as "SCS-MP2 TOTAL ENERGY".
2)  Should we label MP2 as DF-MP2 or DF-SCS-MP2 (in psi.html) since that is what is actually being run?

**Comment by loriab** [comment]
For other reasons, I'm against sticking too much options info in the psivar string. So I vote `MP2 TOTAL ENERGY` or `SCS-MP2 TOTAL ENERGY` rather than any `DF-` variants. But you're right, it sounds like output or psivar parsing could use some `^` & `$` markers to avoid picking up unintended partial matches.

**Comment by CDSherrill** [comment]
Hm, this needs to get fixed.  I'm fine with just accepting that DF is a
good approximation and not worrying about it, but I don't want to get SCS
when the user probably wants non-SCS.

David
